### ISSUE TITLE
Any commands for stopping Elasticache?

### ISSUE THREAD

**Issue by mding5692** [aramalipoor/aws-cost-saver#1]
I use AWS Elasticache for Redis and also can shut that down or stop it to save some costs, really thanks for this project, looking for something like it for a while now!

**Comment by aramalipoor** [comment]
@mding5692 just released `v0.0.7` with `snapshot-remove-elasticache-redis` trick. Give it a try on your development env and let me know if it has any issues :)

Since it's an experimental trick, you can try it by:
```sh
aws-cost-saver conserve --dry-run --use-trick snapshot-remove-elasticache-redis
```
and if it correctly detected your ElastiCache cluster (you can look in the resulting `aws-cost-saver.json` file), then remove the dry run:
```sh
aws-cost-saver conserve --use-trick snapshot-remove-elasticache-redis
```
